### ISSUE TITLE
Archive Command issue

### ISSUE THREAD

**Issue by tanyqcollin** [AY2425S1-CS2103T-W10-4/tp#131]
Did not mention the file path should not have any space and any symbol, ie “my_book.json” and “my book.json”.

**Comment by Jianwen0451** [comment]
When I try using the jar file, it can archive to the file name my_book.json and my book.json

**Comment by Jianwen0451** [comment]
Can I know a more specific context of this is not working?

**Comment by Jianwen0451** [comment]
<img width="1053" alt="Screenshot 2024-11-03 at 9 15 46 PM" src="https://github.com/user-attachments/assets/7e22e203-a76f-4477-886c-2259e22a25d5">
<img width="903" alt="Screenshot 2024-11-03 at 9 16 54 PM" src="https://github.com/user-attachments/assets/1f48000c-38f7-4183-b64d-c3e4c9b0258a">

**Comment by tanyqcollin** [comment]
ow sorry, my mistake. Forget to add `pa/` when i do the testing
