### ISSUE TITLE
Archive Command filename issue

### ISSUE THREAD

**Issue by tanyqcollin** [AY2425S1-CS2103T-W10-4/tp#132]
File paths do not accept filename that contains numbers, ie “CS2103.json”

**Comment by Jianwen0451** [comment]
Same issue here as #131 , can you explain more in what context it does not accept?

**Comment by Jianwen0451** [comment]
<img width="1053" alt="Screenshot 2024-11-03 at 9 15 46 PM" src="https://github.com/user-attachments/assets/e454cde2-d205-41e6-8276-6f7e69505b68">
<img width="903" alt="Screenshot 2024-11-03 at 9 16 54 PM" src="https://github.com/user-attachments/assets/42ee5938-559b-4fd3-99ee-82efa6ac2aed">
