### ISSUE TITLE
Filter Command invalid phone number

### ISSUE THREAD

**Issue by yongqqqq** [AY2425S1-CS2103T-W10-4/tp#148]
When using an invalid value for phone number such as a string literal "abcd". The error message states that it should be at least 3 digits long. This could be misinterpreted as filter accepts any number of integers. While the filter command still functions, it will never be able to display any persons. 

We can consider better input validation to prevent this from happening.

![image](https://github.com/user-attachments/assets/22f95c72-28ff-4ed1-8397-058d3a8ef2da)

**Comment by tanyqcollin** [comment]
what is the "filter accepts any number of integers" mean, because i think i had mention in the error message that the phone number should contains number only

**Comment by yongqqqq** [comment]
To clarify, as per the screenshot, the filter currently will accept the value "123" as a phone number. However, it will not return any person. Henceforth, do we want to check and ensure that the user keys in a 8digit phone number?

**Comment by tanyqcollin** [comment]
ok, now i have updated the functionality for the filter phone number. It should support to filter phone number at least 3 digits.
