### ISSUE TITLE
[PE-D][Tester B] Names accept forward slashes but not if preceded by m

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W10-4/tp#203]
![image.png](https://raw.githubusercontent.com/ethanwangkangen/ped/main/files/135a2e51-1cae-4dfd-869c-9a6592c7aa03.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: ethanwangkangen/ped#5

**Comment by Jianwen0451** [comment]
I guess we just disallow slash or warn user that things like n/ g/ will be recegenisted as prefix.
